// <auto-generated />
using System;
using Dispatcher.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dispatcher.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dispatcher.DAL.Entities.FileProcessingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("HighVolumeKeywordsCount")
                        .HasColumnType("bigint");

                    b.Property<int>("LinesCount")
                        .HasColumnType("int");

                    b.Property<string>("LinkToFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MisspelledKeywordsCount")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SuperTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SuperTaskId");

                    b.ToTable("FileProcessingTasks");
                });

            modelBuilder.Entity("Dispatcher.DAL.Entities.SuperTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SuperTasks");
                });

            modelBuilder.Entity("Dispatcher.DAL.Entities.FileProcessingTask", b =>
                {
                    b.HasOne("Dispatcher.DAL.Entities.SuperTask", "SuperTask")
                        .WithMany("FileProcessingTasks")
                        .HasForeignKey("SuperTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuperTask");
                });

            modelBuilder.Entity("Dispatcher.DAL.Entities.SuperTask", b =>
                {
                    b.Navigation("FileProcessingTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
